import React from 'react'
import Head from 'next/head'
import Navbar from '../Navbar/Navbar'
import Footer from '../Footer/Footer'


const LayoutMain = ({title="E-Cart",children=<></>}) => {
  return (
    <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

    <div>
        <header><Navbar/></header>

        <main>{children}</main>

        <footer> <Footer/> </footer>
    </div>

    </>
  )
}

export default LayoutMain